<a href="https://colab.research.google.com/github/bryanfree66/tensorflow_notebooks/blob/master/tf_python_autograph.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf
import timeit

In [0]:
cell = tf.keras.layers.LSTMCell(100)

In [0]:
@tf.function
def test_fn(input, state):
  return cell(input, state)

In [0]:
input = tf.zeros([100, 100])
state = [tf.zeros([100, 100])] * 2

In [12]:
# warm up
cell(input, state)
test_fn(input, state)

(<tf.Tensor: shape=(100, 100), dtype=float32, numpy=
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)>,
 [<tf.Tensor: shape=(100, 100), dtype=float32, numpy=
  array([[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)>,
  <tf.Tensor: shape=(100, 100), dtype=float32, numpy=
  array([[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)>])

In [13]:
graph_time = timeit.timeit(lambda:
                           cell(input, state),
                           number=100)

print('Graph time: ', graph_time)

Graph time:  0.11611524599993572


In [14]:
auto_graph_time = timeit.timeit(lambda:
                           test_fn(input, state),
                           number=100)
print('Auto graph time: ', auto_graph_time)

Auto graph time:  0.08823339199989277
